name: Build and Deploy Delícias da Fabi
env:
  REGISTRY: sanderson-ggadc8aca3bfgddn.azurecr.io
  IMAGE_NAME: delicias-fabi
  AZURE_WEBAPP_NAME: Sanderson
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: sanderson-ggadc8aca3bfgddn.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build e Push da imagem Docker
        run: |
          docker build -t sanderson-ggadc8aca3bfgddn.azurecr.io/delicias-fabi:${{ github.sha }} .
          docker push sanderson-ggadc8aca3bfgddn.azurecr.io/delicias-fabi:${{ github.sha }}
          docker tag sanderson-ggadc8aca3bfgddn.azurecr.io/delicias-fabi:${{ github.sha }} sanderson-ggadc8aca3bfgddn.azurecr.io/delicias-fabi:latest
          docker push sanderson-ggadc8aca3bfgddn.azurecr.io/delicias-fabi:latest

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update container
        run: |
          az webapp config container set \
            --name Sanderson \
            --resource-group Sanderson \
            --container-image-name sanderson-ggadc8aca3bfgddn.azurecr.io/delicias-fabi:${{ github.sha }}