name: Deploy Delícias da Fabi

env:
  AZURE_WEBAPP_NAME: websander

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy no Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: websander
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
